# Copyright 2026 The Apache Software Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Typed external models for the site pipeline."""

from .base import SitePipelineBaseModel
from .catalog import (
    ArtifactConfig,
    ArtifactLifecycleConfig,
    ArtifactVersioningConfig,
    CandidateSelectionPolicy,
    CatalogDefaults,
    CatalogDocumentV1,
    CompatibilityAssertionConfig,
    ComponentCatalogEntry,
    ComponentContentSelection,
    ExactReleaseConfig,
    GroupConfig,
    LineHeadSelectionPolicy,
    LocalizationConfig,
    MountConfig,
    NamedRefConfig,
    OriginConfig,
    PublicationConfig,
    PublicationDefaults,
    PublicationSelectionPolicy,
    RedirectRuleConfig,
    ReleaseLineConfig,
    ReleaseSelectionPolicy,
    RouteAliasConfig,
    SiteContentConfig,
    SourceConfig,
    SupportWindow,
    TopLevelAssetConfig,
)
from .component_repository import (
    ComponentIdentity,
    ComponentLifecycleHints,
    ComponentRepositoryDocumentV1,
    ContentRoots,
    SupportStatusDefinition,
)
from .enums import (
    CandidateSelectionMode,
    CheckFailureThreshold,
    DiagnosticSeverity,
    DocumentFormat,
    IndexBehavior,
    LineHeadSelectionMode,
    MaterializationInputKind,
    MaterializationStatus,
    PlanningTarget,
    PublicationState,
    RecordKind,
    ReleaseSelectionMode,
    RouteMode,
    RunStatus,
    StageCommand,
    TrustClass,
    WithdrawalBehavior,
)
from .loading import (
    DocumentDecodingError,
    DocumentRootTypeError,
    DocumentSyntaxError,
    DocumentValidationFailure,
    DuplicateKeyError,
    LoadingError,
    MissingSchemaVersionError,
    UnsupportedSchemaVersionError,
    load_check_report,
    load_catalog_document,
    load_component_repository_document,
    load_json_mapping,
    load_provider_snapshot,
    load_resolved_materialization_report,
    load_stage_manifest,
    load_stage_run_report,
    load_versioned_document,
    load_yaml_mapping,
)
from .planning_stage_contract import (
    CheckReportV1,
    CheckSummary,
    PipelineDiagnosticEntry,
    ReducedDiagnosticDetailsSummary,
    ResolvedMaterializationEntry,
    ResolvedMaterializationReportV1,
    StageDataFiles,
    StageManifestV1,
    StageRoots,
    StageRunReportV1,
    StageRunSummary,
)
from .provider_snapshot import ProviderAsset, ProviderDescriptor, ProviderRecord, ProviderSnapshotV1
from .scalars import (
    ArtifactKey,
    ExtensionsObject,
    Identifier,
    LocalPathString,
    MountSourceRef,
    OriginKey,
    ProviderBaseUrl,
    ProviderKey,
    PublicPath,
    RefString,
    ReferenceString,
    RegexString,
    RepoRelativePath,
    SchemaVersion,
    Slug,
    SourceKey,
    StageRelativePath,
    TimestampString,
    UrlString,
    VersionString,
)

__all__ = [
    "ArtifactKey",
    "ArtifactConfig",
    "ArtifactLifecycleConfig",
    "ArtifactVersioningConfig",
    "CandidateSelectionMode",
    "CandidateSelectionPolicy",
    "CatalogDefaults",
    "CatalogDocumentV1",
    "CheckFailureThreshold",
    "CheckReportV1",
    "CheckSummary",
    "CompatibilityAssertionConfig",
    "ComponentCatalogEntry",
    "ComponentContentSelection",
    "ComponentIdentity",
    "ComponentLifecycleHints",
    "ComponentRepositoryDocumentV1",
    "ContentRoots",
    "DiagnosticSeverity",
    "DocumentDecodingError",
    "DocumentFormat",
    "DocumentRootTypeError",
    "DocumentSyntaxError",
    "DocumentValidationFailure",
    "DuplicateKeyError",
    "ExactReleaseConfig",
    "ExtensionsObject",
    "GroupConfig",
    "Identifier",
    "IndexBehavior",
    "LineHeadSelectionPolicy",
    "LineHeadSelectionMode",
    "LocalPathString",
    "LoadingError",
    "MaterializationInputKind",
    "MaterializationStatus",
    "MissingSchemaVersionError",
    "MountConfig",
    "MountSourceRef",
    "NamedRefConfig",
    "OriginConfig",
    "OriginKey",
    "PipelineDiagnosticEntry",
    "PlanningTarget",
    "PublicationConfig",
    "PublicationDefaults",
    "PublicationSelectionPolicy",
    "ProviderAsset",
    "ProviderBaseUrl",
    "ProviderDescriptor",
    "ProviderKey",
    "ProviderRecord",
    "ProviderSnapshotV1",
    "PublicationState",
    "PublicPath",
    "RecordKind",
    "RedirectRuleConfig",
    "RefString",
    "ReferenceString",
    "ReducedDiagnosticDetailsSummary",
    "RegexString",
    "ReleaseLineConfig",
    "ReleaseSelectionMode",
    "ReleaseSelectionPolicy",
    "RepoRelativePath",
    "ResolvedMaterializationEntry",
    "ResolvedMaterializationReportV1",
    "RouteAliasConfig",
    "RouteMode",
    "RunStatus",
    "SchemaVersion",
    "SiteContentConfig",
    "SitePipelineBaseModel",
    "Slug",
    "SourceConfig",
    "SourceKey",
    "StageCommand",
    "StageDataFiles",
    "StageManifestV1",
    "StageRelativePath",
    "StageRoots",
    "StageRunReportV1",
    "StageRunSummary",
    "SupportStatusDefinition",
    "SupportWindow",
    "TimestampString",
    "TopLevelAssetConfig",
    "TrustClass",
    "UnsupportedSchemaVersionError",
    "UrlString",
    "VersionString",
    "WithdrawalBehavior",
    "load_check_report",
    "load_catalog_document",
    "load_component_repository_document",
    "load_json_mapping",
    "load_provider_snapshot",
    "load_resolved_materialization_report",
    "load_stage_manifest",
    "load_stage_run_report",
    "load_versioned_document",
    "load_yaml_mapping",
]