#
# Copyright 2026 The Buildish Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[[bundles]]
image-ref = "docker.io/library/python:3.13-bookworm@sha256:353cf2106d143e1d28f5d7c10c5f5c0387085bba22ef0f7f7e52c2c330fb1779"
name = "python"
version = "3.13-bookworm"
output-key = "python-3.13-bookworm"
home-page = "https://www.python.org/"
license-expression = "Python-2.0"
license-files = ["tools/site-pipeline-image/legal/base-images/python-3.13-bookworm/LICENSE"]
notice-files = []

[[bundles]]
image-ref = "ghcr.io/astral-sh/uv:0.12.0@sha256:606e70c71c852d03f611b1e56a195d08648507018a7057fab82c4974c4eae105"
name = "uv"
version = "0.12.0"
output-key = "uv-0.12.0"
home-page = "https://docs.astral.sh/uv/"
license-expression = "Apache-2.0 OR MIT"
license-files = ["LICENSE", "tools/site-pipeline-image/legal/base-images/uv-0.12.0/LICENSE-MIT"]
notice-files = []
